// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/12/2026, 11:19:23 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/plugins/**/*.{js,ts,mjs}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/composables/**/*.{js,ts,mjs}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/utils/**/*.{js,ts,mjs}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/cyriljosef/Documents/GitHub/valenTINE/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;